### ISSUE TITLE
Analysis does not start when opening stand-alone cnfg files

### ISSUE THREAD

**Issue by einarsi** [equinor/vscode-septic#169]
Files that are referenced in scg yaml configs are analysed as soon as they are opened, and it seems also as if related files are analysed and/or edited (e.g. if one of the cnfg templates is opened, then all cnfg templates are analysed). That's great.

However, cnfg files not referenced in scg yaml config are not analysed until they are edited. All SEPTIC files should be analysed when they are opened. If they are part of an scg context, then they should be analysed in that context. If they are stand-alone, then they should be analysed as stand-alone.

I have a minimal test case available if you want a demo.

**Comment by vetlek** [comment]
When the extension is started, the workspace is scanned for scg configs and related cnfg files are added to the active environment. Standalone cnfgs are supposed to be loaded when they are opened, but not done currently. This is going to be fixed in #171. We can discuss if it is preferable that all standalone files are also added to the active context when the extension starts.

**Comment by vetlek** [comment]
Fixed in #171 . Reopen if needed.
